### PR TITLE
Update extract_verbs.sh

### PR DESCRIPTION
**Pull request by abhishekikc**
I have done the following changes:
1. Added more languages(now 20 languages) for which treetagger parameter file exists.
2. Taken LANGUAGE as input to the script. This can be directly taken to access the treetagger instance by tree-tagger-"$LANGUAGE".
3. Using LANGUAGE to assign LANGCODE in each case.

### CODE REVIEW

**Comment by abhishekikc** [comment]
I think bag_of_words.py file is terminating Stop words from the extracted vocabulary. Then how would it be compatible with all the languages?

**Comment by marfox** [comment]
You are right @abhishekikc, I'll file an issue for that, but it's not a priority, since the script you are mentioning is not actually required for the workflow to run.

However, it would be a cool warm-up task to add the stop word lists for all the supported languages.

**Comment by marfox** [comment]
Please make sure your indentation is set to 4 spaces (soft tab)

**Comment by abhishekikc** [comment]
I have re-indented it.

**Pull request merged**
