### PR TITLE
Fix for ticket #38

### PR DESCRIPTION
**Pull request by e-dorigatti**
Here's the pull request. I also refactored the file into functions and added docstrings.

I have found a case in which a file was missing the initial token of a chunk, currently I basically ignore it but this might indicate a problem with textpro. The sentence id is 33 and the relevant section is [this](https://github.com/e-dorigatti/fact-extractor/blob/chunk-combo/combine_chunks.py#L78)

### CODE REVIEW

**Comment by marfox** [comment]
Fails with:
```python
Traceback (most recent call last):
  File "combine_chunks.py", line 210, in <module>
    main()
  File "combine_chunks.py", line 197, in main
    all_chunks = load_chunks(path)
  File "combine_chunks.py", line 112, in load_chunks
    sentence, link_chunks = read_twm_links(f)
NameError: global name 'read_twm_links' is not defined
```
Did you just rename that function to `read_twm_links_and_ngrams` or is there something more?

**Comment by e-dorigatti** [comment]
No, it's just a naming issue. I noticed that the two functions are
basically the same so I wanted to merge them into one, but since the file
format is actually different I decided to keep them separated. I think I
messed up my commits :)
I will fix this in an hour or two

**Comment by e-dorigatti** [comment]
It should work now

**Comment by marfox** [comment]
Great job

**Pull request merged**
