### PR TITLE
Fix for issue #32

### PR DESCRIPTION
**Pull request by e-dorigatti**
So I had to change quite a lot of things because tokens have to be identified using their position and not the actual word and I basically rewrote the entire tag creation procedure.
I aligned the sample treetagger output to match the new crowdflower sample and added one test sentence to it to make sure I didn't break the fix for issue #9.

### CODE REVIEW

**Comment by marfox** [comment]
Great job, thanks!
However, there seems to be a bug.
I checked the debug output of the script using the sample inputs, i.e.:
```
python crowdflower_results_into_training_data.py -d resources/crowdflower-results.sample resources/treetagger-output-sample/ resources/training-data.sample
```
`Amkar Perm` in sentence `79` is tagged with `O`, while the crowdflower results correctly annotate it with `Squadra`. See debug:
```
   "11": {
      "majority": "Squadra",
      "word": "Amkar",
      "answers": [
        "Squadra"
      ],
      "judgments": 1
    },
    "12": {
      "majority": "Squadra",
      "word": "Perm",
      "answers": [
        "Squadra"
      ],
      "judgments": 1
    }
```
but
```
[u'79', '12', u'Amkar', u'NOM', u'<unknown>', u'Attivit\xe0', 'O']
[u'79', '13', u'Perm', u'NOM', u'<unknown>', u'Attivit\xe0', 'O']
```
Can you please check?

**Comment by e-dorigatti** [comment]
The problem appears to be a misalignment between the tokens in the input file and those found by treetagger.

This is what treetagger found:
```
si	PRO:pers	si
trasferisce	VER:pres	trasferire
all'	PRE:det	al
Amkar	NOM	<unknown>
Perm	NOM	<unknown>
```

Whereas the tokens listed in the input file are `,si,,trasferisce,,all,,Amkar,,Perm,` (notice the missing apostrophe).

**Comment by marfox** [comment]
I see, this must be caused by different tokenizations.
A quick and dirty way would be simply to remove trailing non-letters 
when parsing the token column of the TreeTagger input.
This can be a workaround for now.

But can you think of a more robust approach?

**Comment by e-dorigatti** [comment]
Ideally this script shouldn't handle this problem because it is related to its input only, but depending on how the csv from crowdflower is generated this might be feasible or not. (maybe [this](https://github.com/dbpedia/fact-extractor/blob/master/create_crowdflower_input.py)?)

If not, the script could simply replace the tokens found in the input csv with the ones from treetagger (or the other way around, it shouldn't make any difference) using an heuristic such as the [Levenshtein distance](http://en.wikipedia.org/wiki/Levenshtein_distance) or the [minimum edit distance](http://en.wikipedia.org/wiki/Edit_distance) to make sure that the replacement is actually correct. In fact, I expect such distances to assume values below 1 or 2 since the mistakes we are trying to catch are most probably related to punctuation only.

**Comment by marfox** [comment]
I see your point: it makes sense, but we should avoid introducing 
potentially wrong matches.
If the problem is only punctuation, we should just ignore the 
corresponding lines in treetagger, what do you think?

**Comment by e-dorigatti** [comment]
No, I don't see how we could do that; the tokens from treetagger and the input dataset should correspond because I use them for matching entities and understand what token belongs to what entity ([here](https://github.com/dbpedia/fact-extractor/pull/33/files#diff-2f2cf27efbc40910cd4c3fabfac5b44bR149)).

**Comment by marfox** [comment]
You make them correspond by removing the misalignment in the tokenization.
The thins is simple: when I prepare the crowdflower input, I split on 
punctuations and discard thema, since I don't want them to be annotated 
*anyway*.
I keep dashes, since they may trigger date periods like 1923-1924 and I 
want them to be annotated.
Treetagger seems to split on everything and to keep everything.
So we don't really need those tokens I think.

**Comment by e-dorigatti** [comment]
I think this should be the topic of another ticket, it's not as straightforward as it looks like. There are some details to settle and discuss

**Pull request closed without merging**
